### ISSUE TITLE
no verb realization

### ISSUE THREAD

**Issue by miwieg** [bjascob/pySimpleNLG#4]
I tried some basic example with pySimplNLG. However, verbs are systematically omitted from the final output.

I used the following code:

`import simplenlg as nlg

nlg_factory = nlg.NLGFactory()
lexicon = nlg.lexicon.Lexicon()
realiser = nlg.realiser.Realiser(lexicon)

p = nlg_factory.createClause()
p.setSubject("The dog")
p.setVerb("bite")
p.setObject("the monkey")
p.setFeature(nlg.Feature.TENSE,nlg.Tense.PAST)
print(realiser.realiseSentence(p))`

which only produces

> The dog the monkey.

Just to make sure, I also checked the original JAVA-code from which this package has been built.
That code does create proper sentences with verbs. So I guess there must be a bug in the python version.

**Comment by bjascob** [comment]
A quick look at this shows that the VP is not getting modified when you do `p.setVerb('bite')` and only the original empty VP is present.  You can see this by putting in `print( p )` before and after the `setVerb`.

I'm not sure why this is happening.  I'll try to look at it if I get some time but that might be a while.

**Comment by bjascob** [comment]
This will work if you setup the realiser with the following code...
```
lexicon = nlg.lexicon.Lexicon.getDefaultLexicon()
nlg_factory = nlg.NLGFactory(lexicon)
realiser = nlg.realiser.Realiser(lexicon)
```

This is how the java wiki shows the code being setup (see https://github.com/simplenlg/simplenlg/wiki/Section-III-%E2%80%93-Getting-started)

Can you tell me where you found the code example for your realiser setup (ie... not using `getDefaultLexicon()`) and how/where you tested the java code?  I'm not seeing how this would work without setting the lexicon.

**Comment by bjascob** [comment]
Closing as no bug exists in the code.  The python code works the same as the java.
The original code posted by the user does not run correctly under java...

1. Lexicon is an abstract base class and can not be directly instantiated.  The user needs to use `Lexicon.getDefaultLexicon()` per the java examples.
2.  `lexicon` must be passed into the declaration of `NLGFactory(` or the verb will not appear in the phrase.  While this may not be intuitive, this is the way the java code works.

**Comment by miwieg** [comment]
Thank you very much for clarifying this. With your code modification I could now replicate the requested output.
I got the incorrect code example from a colleague -- next time I should be more critical when I will be given such examples.
Again many thanks again.
